In [2]:
import numpy as np
from matplotlib.pyplot import plot, cm, show
import matplotlib.pyplot as plt

%matplotlib inline

# PC AGE Career Institute Path Train Ad Problem:

## (Seen on the NJ Transit Path Train)

### "Your Either Have IT of You Dont"

### "What comes next?"

# IT Subway Ad: Calculations:

In [3]:
A = np.array([3,4,6,9,13,18,24,31,39,48,58,69,81,94,108])

A_diff = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

print('\n Given Array')
print(A)

print('\n Array of Step Differences')
print(A_diff)


 Given Array
[  3   4   6   9  13  18  24  31  39  48  58  69  81  94 108]

 Array of Step Differences
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# $ \text{Recursive Function:} \quad a_{(n)}$

$ \Huge A_0 = 3 $

$ \Huge A_n = A_{n-1} + n , \qquad m,n \in \mathbb{N}, \quad n \in \text{{1, 2, 3, ....., m}}$

In [4]:
def a_n(n):
    
    if n == 0:
        return 3
    else:
        return a_n(n-1) + n

# $ \text{Application of Recursive Function:} \quad a_{(n)}$

In [6]:
lo = 0
hi = 15
n = np.arange(lo,hi + 1)

len_n = len(n)

a_n_array = np.empty(0)

for i in range(len_n):
#     print(a_n(i))
    a_n_array = np.append(a_n_array, a_n(i))

print('\n n array')
print(n)

print('\n a_n array')
print(a_n_array)


 n array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 a_n array
[  3.   4.   6.   9.  13.  18.  24.  31.  39.  48.  58.  69.  81.  94.
 108. 123.]


# $ \text{Non-Recursive Function:} \quad a_{(k)}$

# $ \text{Uses Sums}$

$ \Huge A_0 = 3 $

$ \Huge A_k = A_0 + \sum\limits_{i=1}^k i , \qquad k,n \in \mathbb{N}, \quad k \in \text{{1, 2, 3, ....., n}}$

In [7]:
def a_k(k):
    
    a_0 = 3
    
    k_list = []
    
    for i in range(1,k+1):
        k_list.append(i)
    
    if k == 0:
        return 3
    
    else:
        return a_0 + sum(k_list)

# $ \text{Application of Non-Recursive Function:} \quad a_{(k)}$

In [9]:
a_0 = 3

lo = 0
hi = 15
n = np.arange(lo,hi + 1)

len_n = len(n)

# print(n)

for i in range(len_n):
    print(a_k(i))

3
4
6
9
13
18
24
31
39
48
58
69
81
94
108
123


# Application of Both Functions:

In [11]:
a_0 = 3

lo = 0
hi = 15
n = np.arange(lo,hi + 1)

len_n = len(n)

a_n_1 = np.empty(0)
a_n_2 = np.empty(0)

for i in range(len_n):
    a_n_1 = np.append(a_n_1, a_n(i))
    a_n_2 = np.append(a_n_2, a_k(i))

print('\n a_n array')
print(a_n_1)

print('\n a_k array')
print(a_n_2)

print('\n a_n array == a_k array')
print(np.allclose(a_n_1, a_n_2))


 a_n array
[  3.   4.   6.   9.  13.  18.  24.  31.  39.  48.  58.  69.  81.  94.
 108. 123.]

 a_k array
[  3.   4.   6.   9.  13.  18.  24.  31.  39.  48.  58.  69.  81.  94.
 108. 123.]

 a_n array == a_k array
True


# Differences in Steps:

In [12]:
for i in range(len_n-1):
    print('Difference between ', a_n_1[i], ' and ' , a_n_1[i+1], ' is ', n[i+1])

Difference between  3.0  and  4.0  is  1
Difference between  4.0  and  6.0  is  2
Difference between  6.0  and  9.0  is  3
Difference between  9.0  and  13.0  is  4
Difference between  13.0  and  18.0  is  5
Difference between  18.0  and  24.0  is  6
Difference between  24.0  and  31.0  is  7
Difference between  31.0  and  39.0  is  8
Difference between  39.0  and  48.0  is  9
Difference between  48.0  and  58.0  is  10
Difference between  58.0  and  69.0  is  11
Difference between  69.0  and  81.0  is  12
Difference between  81.0  and  94.0  is  13
Difference between  94.0  and  108.0  is  14
Difference between  108.0  and  123.0  is  15


# Condensed:

In [13]:
a_0 = 3

lo = 0

# Change this value:
hi = 15

n = np.arange(lo,hi + 1)

len_n = len(n)

a_n_1 = np.empty(0)
a_n_2 = np.empty(0)

for i in range(len_n):
    a_n_1 = np.append(a_n_1, a_n(i))
    a_n_2 = np.append(a_n_2, a_k(i))

print('\n a_n array')
print(a_n_1)

print('\n a_k array')
print(a_n_2)

print('\n Differences in Steps:')

for i in range(len_n-1):
#     print('\t')
    print('Difference between ', a_n_1[i], ' and ' , a_n_1[i+1], ' is ', n[i+1])


 a_n array
[  3.   4.   6.   9.  13.  18.  24.  31.  39.  48.  58.  69.  81.  94.
 108. 123.]

 a_k array
[  3.   4.   6.   9.  13.  18.  24.  31.  39.  48.  58.  69.  81.  94.
 108. 123.]

 Differences in Steps:
Difference between  3.0  and  4.0  is  1
Difference between  4.0  and  6.0  is  2
Difference between  6.0  and  9.0  is  3
Difference between  9.0  and  13.0  is  4
Difference between  13.0  and  18.0  is  5
Difference between  18.0  and  24.0  is  6
Difference between  24.0  and  31.0  is  7
Difference between  31.0  and  39.0  is  8
Difference between  39.0  and  48.0  is  9
Difference between  48.0  and  58.0  is  10
Difference between  58.0  and  69.0  is  11
Difference between  69.0  and  81.0  is  12
Difference between  81.0  and  94.0  is  13
Difference between  94.0  and  108.0  is  14
Difference between  108.0  and  123.0  is  15


# Combination:

$ \huge  A_0 = 3 $

$ \huge \newline$

$ \huge \text{Recursive Function:} \quad a_{(n)}$

$ \huge A_n = A_{n-1} + n , \qquad m,n \in \mathbb{N}, \quad n \in \text{{1, 2, 3, ....., m}}$

$ \huge \newline$

$ \huge \text{Let n = k}$

$ \huge \newline$

$ \huge \text{Recursive Function:} \quad a_{(n)} \quad \rightarrow \quad a_{(k)}$

$ \huge \newline$

$ \huge A_k = A_{k-1} + k , \qquad k,m \in \mathbb{N}, \quad k \in \text{{1, 2, 3, ....., m}}$

$ \huge \newline$

$ \huge \text{Non-Recursive Function:} \quad a_{(k)}$

$ \huge A_k = A_0 + \sum\limits_{i=1}^k i , \qquad k,m \in \mathbb{N}, \quad k \in \text{{1, 2, 3, ....., m}}$

$ \huge \text{Equate both } A_k \text{ functions}$

$ \huge A_k = A_k$

$ \huge A_{k-1} + k = A_0 + \sum\limits_{i=1}^k i$

$ \huge A_{k-1} = A_0 + \sum\limits_{i=1}^k i \quad - k$

$ \huge \newline$

$ \large \text{Iterate up one step } k-1 \rightarrow k$

$ \huge A_{k-1+1} = A_k = A_0 + \sum\limits_{i=1}^{k+1} i \quad - (k + 1)$

$ \huge A_k = A_0 + \sum\limits_{i=1}^{k+1} i \quad - (k + 1)$

$ \huge \newline$

$ \large \text{Iterate up one step } k \rightarrow k+1$

$ \huge A_{k+1} = A_0 + \sum\limits_{i=1}^{k+2} i \quad - (k + 2)$

$ \huge \newline$

$ \large \text{Iterate up n steps } k \rightarrow k+n$

$ \huge A_{k+n} = A_0 + \sum\limits_{i=1}^{k + n + 1} i \quad - (k + n + 1)$

$ \huge \text{Three new } A_k \text{ functions:}$

$ \huge \newline$

$\huge k,n \in \mathbb{N}, \quad k \in \text{{1, 2, 3, ....., n}}$

$ \huge \newline$

$ \huge A_k = A_0 + \sum\limits_{i=1}^{k+1} i \quad - (k + 1)$

$ \huge \newline$

$ \huge A_{k+1} = A_0 + \sum\limits_{i=1}^{k+2} i \quad - (k + 2)$

$ \huge \newline$

$ \huge A_{k+n} = A_0 + \sum\limits_{i=1}^{k + n + 1} i \quad - (k + n + 1)$

# $ \text{Non-Recursive Functions 2 and 3:} \quad a_{(k)} \text{and} \quad a_{(k+n)}$

## $ \text{Both Use Sums}$

$\huge k,n \in \mathbb{N}, \quad k \in \text{{1, 2, 3, ....., n}}$

$ \huge \newline$

$ \huge A_k = A_0 + \sum\limits_{i=1}^{k+1} i \quad - (k + 1)$

In [20]:
def a_k1(k):
    
    a_0 = 3
    
    k_list = []
    
#     k + 1 and then
#     k + 1 + 1 for the proper list length
#     thus k + 2

    k_plus_one = k + 2

    for i in range(1,k_plus_one):
        k_list.append(i)
    
    if k == 0:
        return 3
    
    elif (k or n) < 0:
        return 'error'
    
    else:
        return a_0 + sum(k_list) - ( k + 1 )

$\huge k,n \in \mathbb{N}, \quad k \in \text{{1, 2, 3, ....., n}}$

$ \huge \newline$

$ \huge A_{k+n} = A_0 + \sum\limits_{i=1}^{k + n + 1} i \quad - (k + n + 1)$

In [21]:
def a_plus_n(k,n):
    
    a_0 = 3
    
    k_list = []

#     k + n + 1 and then
#     k + n + 1 + 1 for the proper list length
#     thus k + n + 2

    k_n_pls_two = k + n + 2

    for i in range(1,k_n_pls_two):
        k_list.append(i)
    
    ##########################################
    
    # Case of k = 0 and n > 0:
    m_list = []
    
    m = n

#     if (k == 0 and n > 0):
#         m = n
    
#     m + 1 and then
#     m + 1 + 1 for the proper list length
#     thus m + 2
    m_plus_one = m + 2

    for i in range(1,m_plus_one):
        m_list.append(i)

    m_sum = a_0 + sum(m_list) - ( m + 1 )
        
    ##########################################

    if ( (k == 0) and (n > 0) ):
        return m_sum
    
    elif k == 0:
        return 3

    elif (k < 0) or (n < 0):
        return 'error'
    
    else:
        return a_0 + sum(k_list) - ( k + n + 1 )

# $ \text{Testing the New Non-Recursive Functions 2 and 3:} \quad a_{(k)} \text{and} \quad a_{(k+n)}$

In [93]:
k = 15+1

for i in range(k):
    print('A_',i,' = ',a_k1(i))

A_ 0  =  3
A_ 1  =  4
A_ 2  =  6
A_ 3  =  9
A_ 4  =  13
A_ 5  =  18
A_ 6  =  24
A_ 7  =  31
A_ 8  =  39
A_ 9  =  48
A_ 10  =  58
A_ 11  =  69
A_ 12  =  81
A_ 13  =  94
A_ 14  =  108
A_ 15  =  123


In [105]:
sz = 2

steps = 10

max_val = 15 + 1

print('\n No Negative Values:')

# No Negative Values:
for i in range(steps):
    rand_arr = np.random.randint(max_val, size = sz)
    
    k = rand_arr[0]
    n = rand_arr[1]
    
    print('A_',k ,'+',n ,'    = ','A_', k + n,'_ =    ', a_plus_n(k,n))

print('\n With Possible Negative Values:')

# With Possible Negative Values:
for i in range(steps):
    rand_arr = np.random.randint(max_val, size = sz)
    
    neg_val = (-1)**(rand_arr[0])

    k = rand_arr[0] * neg_val
    n = rand_arr[1]

    print('A_',k ,'+',n ,'    = ','A_', k + n,'_ =    ', a_plus_n(k,n))


 No Negative Values:
A_ 1 + 2     =  A_ 3 _ =     9
A_ 8 + 13     =  A_ 21 _ =     234
A_ 8 + 15     =  A_ 23 _ =     279
A_ 13 + 3     =  A_ 16 _ =     139
A_ 10 + 13     =  A_ 23 _ =     279
A_ 14 + 5     =  A_ 19 _ =     193
A_ 8 + 15     =  A_ 23 _ =     279
A_ 11 + 12     =  A_ 23 _ =     279
A_ 10 + 12     =  A_ 22 _ =     256
A_ 0 + 11     =  A_ 11 _ =     69

 With Possible Negative Values:
A_ 12 + 7     =  A_ 19 _ =     193
A_ 12 + 10     =  A_ 22 _ =     256
A_ -3 + 8     =  A_ 5 _ =     error
A_ -3 + 14     =  A_ 11 _ =     error
A_ 14 + 4     =  A_ 18 _ =     174
A_ 8 + 13     =  A_ 21 _ =     234
A_ -5 + 1     =  A_ -4 _ =     error
A_ 0 + 5     =  A_ 5 _ =     18
A_ 4 + 4     =  A_ 8 _ =     39
A_ 14 + 7     =  A_ 21 _ =     234
